### ISSUE TITLE
怎么能看懂这些算法呢

### ISSUE THREAD

**Issue by ssytech** [satjd1996/jobshop#1]
最近想了解jobshop的问题，你的这个项目代码里的算法看不懂呀，有没有资料或者视频，介绍这些内容的。
谢谢！

**Comment by satjd** [comment]
这个是我们课程的大作业，主要是实现了三个不同的算法，你可以先看一下我的报告，不懂的问题我们可以再讨论。我的邮箱noah.songao@gmail.com，资料在下面链接
https://drive.google.com/drive/folders/0B6QHKHAXC8fxdUwwLWJFalhNY0E

**Comment by ssytech** [comment]
谢谢，我先结合你的报告再看一下，有问题再请教你。
